name: CI (Build & Test)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  backend-build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: ./backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

    # 테스트 코드가 있다면 아래 주석을 해제하세요
    # - name: Run tests
    #   run: npm run test

  frontend-user-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend-user

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: ./frontend-user/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

  frontend-admin-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend-admin

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: ./frontend-admin/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
